### ISSUE TITLE
Keyboard layout handler settings do not survive reboot

### ISSUE THREAD

**Issue by tigran123** [raspberrypi-ui/rc_gui#39]
Superficially this sounds similar to issue #4 but it is not quite the same. Namely, I have added a "Keyboard Layout Handler" to the panel for switching between GB and RU (phonetic) layouts (via Ctrl-Shift). This works in the current session, but as soon as I reboot the Keyboard Layout Handler in the panel is left with just gb.

In theory this would be no big deal if I could workaround by executing a command in the terminal like this:

```
$ setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll gb,ru
```

However, this would provide only the Russian typewriter layout and not the Russian phonetic layout. I don't know how to specify the phonetic variant on the setxkbmap command line (it is not obvious from the manpage).

Anyway, the correct fix is for these settings to survive reboot.

**Comment by tigran123** [comment]
I have figured out the command to specify the variant, so this bug is no longer as critical as it was:

```
$ setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll gb,ru -variant ',phonetic'
```

**Comment by spl237** [comment]
The latest version of rc_gui now sets the keyboard in /etc/default/keyboard, so this should now be fixed.

**Comment by kz282** [comment]
I have experienced the same issue on a Pi 4 with a fresh Buster installation with LXPanel 0.10.0.

After editing the Keyboard Layout Handler settings, the new settings are not written to ~/.config/lxpanel/LXDE-pi/panels/panel after clicking the Close button on the dialog. It looks like the close button does nothing.

I have found a workaround: 
1. Edit the keyboard layout settings
2. Close the keyboard layout settings / You don't even need to do this...
3. Open the Panel Settings dialog
4. Close the Panel Settings dialog
And the keyboard layout configuration is written to the disk.

Now the settings survive shutdown / restart, reboot etc.

**Comment by ant-222** [comment]
@spl237

> The latest version of rc_gui now sets the keyboard in /etc/default/keyboard, so this should now be fixed.

This error is still persent in a Raspbian downloaded a week ago.

**Comment by spl237** [comment]
It is not an error - you are using an unsupported plugin. The keyboard language should be set using the Raspberry Pi Configuration or Mouse and Keyboard Settings applications. The plugin you are using sets keyboard language using a non-standard method.

**Comment by ant-222** [comment]
Oh. But:

    Preferences -> Keyboard and Mouse -> Keyboard

will not let me define two layouts for a bilingual user. What *Raspberri Pi Configuraiton* do you mean?

**Comment by ant-222** [comment]
spl237:

> It is not an error - you are using an unsupported plugin.

Then is it an error that that plugin was available in my *LXDE* out-of-the-box?

**Comment by spl237** [comment]
We ship all the plugins that LXDE provide, and add our own as well. (If we removed the LXDE ones, we'd get complaints.) If an LXDE plugin - which this is - doesn't work properly (as indeed some don't), raise an issue with the LXDE authors, not with us.

Bilingual support is not a high priority, particularly given the current situation in the world.
